# -*- coding: utf-8 -*-

"""
Tipos de colunas suportadas

"""


INTEGER = "INTEGER"
TEXT = "TEXT"
PRIMARY_KEY_AUTOINCREMENT = "PRIMARY KEY AUTOINCREMENT"
INTEGER_PRIMARY_KEY_AUTOINCREMENT = "INTEGER PRIMARY KEY AUTOINCREMENT"

